export const endPoints = {
  authentication: {
    login: '/auth/login',
  },
  profile: {
    profile_update: '/profile/update',
    password_update: '/profile/update-password',
    info: '/profile/info',
  },
  index: {
    role:           '/user-access/role',
    department:     '/user-access/department',
    departmentRole: '/user-access/department-role',
    route:          '/user-access/route',
    permission:     '/user-access/permission',
    user:           '/user',
    submaster:      '/submaster/:model',
    customer:       '/contact-management/customer',
    customer_relation: '/contact-management/customer/:customer_id/:relation',
    contact_group: '/contact-management/contact-group',
    update_delete_request: '/update-delete-requests/:model/:action',
    spare:          '/spare-management/part-number',
    sales_log: '/sales-management/sales-log/',
    material_request: '/purchase/material-request/',
    prfq: '/purchase/rfq/',
    purchase_quotation: '/purchase/quotation/',
  },
  list: {
    role:           '/user-access/role',
    department:     '/user-access/department',
    departmentRole: '/user-access/department-role',
    route:          '/user-access/route',
    user:           '/user',
    submaster:      '/submaster/:model',
    customer:       '/contact-management/customer/list',
    contact_group:       '/contact-management/contact-group/list',
    sales_log:      '/sales-management/sales-log/list',
    material_request: '/purchase/material-request/list',
    prfq: '/purchase/rfq/list',
    purchase_quotation: '/purchase/quotation/list',
    quotation_items : '/purchase/quotation/:id/items',
    alternate_parts: '/spare-management/part-number/:id/alternates',
    quotation_by_rfq: '/purchase/quotation/by-rfq/:id',
  },
  info: {
    role:           '/user-access/role/:id',
    department:     '/user-access/department/:id',
    departmentRole: '/user-access/department-role/:id',
    route:          '/user-access/route/:id',
    permission:     '/user-access/permission/:id',
    user:           '/user/:id',
    submaster:      '/submaster/:model/:id',
    customer:       '/contact-management/customer/:id',
    contact_group: '/contact-management/contact-group/:id',
    spare:          '/spare-management/part-number/:id',
    sales_log: '/sales-management/sales-log/:id',
    material_request: '/purchase/material-request/:id',
    prfq: '/purchase/rfq/:id',
    purchase_quotation: '/purchase/quotation/:id',
  },
  create: {
    role:           '/user-access/role',
    department:     '/user-access/department',
    departmentRole: '/user-access/department-role',
    route:          '/user-access/route',
    permission:     '/user-access/permission',
    user:           '/user',
    submaster:      '/submaster/:model',
    customer:       '/contact-management/customer',
    contact_group: '/contact-management/contact-group',
    contact_manager:    '/contact-management/customer/:customer_id/contact-managers',
    shipping_address:   '/contact-management/customer/:customer_id/shipping-addresses',
    bank:               '/contact-management/customer/:customer_id/banks',
    principle_of_owner: '/contact-management/customer/:customer_id/principle-owners',
    trader_reference:   '/contact-management/customer/:customer_id/trader-references',
    spare:          '/spare-management/part-number',
    sales_log: '/sales-management/sales-log/',
    material_request: '/purchase/material-request/',
    prfq: '/purchase/rfq/',
    purchase_quotation: '/purchase/quotation/',
    quotation_items: '/purchase/quotation/:id/items'
  },
  update: {
    role:           '/user-access/role/:id',
    department:     '/user-access/department/:id',
    departmentRole: '/user-access/department-role/:id',
    route:          '/user-access/route/:id',
    permission:     '/user-access/permission/:id',
    user:           '/user/:id',
    submaster:      '/submaster/:model/:id',
    customer:       '/contact-management/customer/:id',
    contact_group: '/contact-management/contact-group/:id',
    contact_manager:    '/contact-management/customer/:customer_id/contact-managers/:id',
    shipping_address:   '/contact-management/customer/:customer_id/shipping-addresses/:id',
    bank:               '/contact-management/customer/:customer_id/banks/:id',
    principle_of_owner: '/contact-management/customer/:customer_id/principle-owners/:id',
    trader_reference:   '/contact-management/customer/:customer_id/trader-references/:id',
    spare:          '/spare-management/part-number/:id',
    sales_log: '/sales-management/sales-log/:id',
    material_request: '/purchase/material-request/:id',
    prfq: '/purchase/rfq/:id',
    purchase_quotation: '/purchase/quotation/:id',
    quotation_line_item: '/purchase/quotation/:quotation/line-items/:line_item',
  },
  delete: {
    role:           '/user-access/role/:id',
    department:     '/user-access/department/:id',
    departmentRole: '/user-access/department-role/:id',
    route:          '/user-access/route/:id',
    permission:     '/user-access/permission/:id',
    user:           '/user/:id',
    submaster:      '/submaster/:model/:id',
    customer:       '/contact-management/customer/:id',
    contact_group: '/contact-management/contact-group/:id',
    contact_manager:    '/contact-management/customer/:customer_id/contact-managers/:id',
    shipping_address:   '/contact-management/customer/:customer_id/shipping-addresses/:id',
    bank:               '/contact-management/customer/:customer_id/banks/:id',
    principle_of_owner: '/contact-management/customer/:customer_id/principle-owners/:id',
    trader_reference:   '/contact-management/customer/:customer_id/trader-references/:id',
    spare:          '/spare-management/part-number/:id',
    quotation_line_item : '/purchase/quotation/:quotation/line-items/:id'
  },
  drop_downs: {
    user:     '/user/drop-downs',
    customer: '/contact-management/customer/drop-downs',
    spare:    '/spare-management/part-number/drop-downs',
    department_role:    '/user-access/department-role/drop-downs',
    sales_log:  '/sales-management/sales-log/drop-downs',
    material_request: '/purchase/material-request/drop-downs',
    prfq: '/purchase/rfq/drop-downs',
    purchase_quotation: '/purchase/quotation/drop-downs',
  },
  others: {
    upload:                    '/media/upload',
    customer_status_update:    '/contact-management/customer/:id/status',
    check_existing_unique_customers:         '/contact-management/customer/check-existing-unique-customers',
    check_existing_unique_banks:             '/contact-management/customer/check-existing-unique-banks',
    check_existing_unique_contact_managers:  '/contact-management/customer/check-existing-unique-contact-managers',
    check_existing_unique_shipping_addresses:'/contact-management/customer/check-existing-unique-shipping-addresses',
    check_existing_unique_trader_references: '/contact-management/customer/check-existing-unique-trader-references',
    check_existing_unique_principle_of_owners:'/contact-management/customer/check-existing-unique-principle-owners',
    check_existing_unique_spares:            '/spare-management/part-number/check-existing-unique',
    update_delete_request_dashboard:         '/update-delete-requests/dashboard',
    process_request:                         '/update-delete-requests/process/:change_id/:action',
    update_delete_request_history:           '/update-delete-requests/history/:record_id',
    create_alternate_spares:                 '/spare-management/part-number/map-alternates',
    contact_group_members: '/contact-management/contact-group/:id/members',
  },
  bulk_upload: {
    customer:        '/contact-management/customer/bulk-upload',
    contact_manager: '/contact-management/customer/contact-managers/bulk-upload',
    shipping_address:'/contact-management/customer/shipping-addresses/bulk-upload',
    bank:            '/contact-management/customer/banks/bulk-upload',
    principle_of_owner:'/contact-management/customer/principle-owners/bulk-upload',
    trader_reference:'/contact-management/customer/trader-references/bulk-upload',
    spare:           '/spare-management/part-number/bulk-upload',
  },
  preview: {
    customer: 'preview-pdf/customer/:id',
    spare:    'preview-pdf/part-number/:id',
    sales_log:    'preview-pdf/sales-log/:id',
    material_request:    'preview-pdf/material-request/:id',
    prfq: '/preview-pdf/prfq/:id',
  },
    preview_post: {
    sales_log:    'preview-pdf/sales-log',
    material_request:    'preview-pdf/material-request',
    prfq: '/preview-pdf/prfq/',
  },
  search: {
    spare: '/spare-management/part-number/search',
  },
  permission: {
  byDeptRole:      '/user-access/permission/department-role/:id',
  saveForDeptRole: '/user-access/permission/department-role/:id',
},
} as const;